### ISSUE TITLE
The error message is not showing properly

### ISSUE THREAD

**Issue by Absleepy** [lightrun-platform/lightrun-k8s-operator#17]
Hi,
I was scrolling around the lightrun and saw this UI issue on the "Book a Demo" form. The error message says "Please complete this required field." But it's not properly visible.
I thought you might want to fix this.

Here is the screenshot.
![Screenshot from 2024-01-04 19-11-12](https://github.com/lightrun-platform/lightrun-k8s-operator/assets/59653077/a07debfc-d1f0-41f4-9cbd-146a199a3cab)

**Comment by Len4i** [comment]
Hi @Absleepy,
It is not related to the k8s operator, but I'll, for sure, forward it to the appropriate team.
Thanks for reporting!
